import { SectionDefinition, SectionType } from './types'

export const SECTION_DEFINITIONS: SectionDefinition[] = [
  {
    type: 'header',
    label: 'Header',
    description: 'Navigation bar with logo and links',
    fields: [
      { key: 'logo', label: 'Logo Text', type: 'text' },
      { key: 'navLinks', label: 'Nav Links (comma-separated)', type: 'text' },
      { key: 'navUrls', label: 'Nav URLs (comma-separated)', type: 'text' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
      { key: 'textColor', label: 'Text Color', type: 'color' },
      { key: 'stickyHeader', label: 'Sticky Header', type: 'checkbox' },
      { key: 'compactHeader', label: 'Compact Header', type: 'checkbox' },
    ],
    defaults: {
      logo: 'MyBrand',
      navLinks: 'Home,About,Services,Contact',
      navUrls: '#,#,#,#',
      bgColor: '#ffffff',
      textColor: '#1a1a1a',
      stickyHeader: 'true',
      compactHeader: 'true',
    },
  },
  {
    type: 'hero',
    label: 'Hero',
    description: 'Full-width banner with headline and CTA',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
      { key: 'ctaText', label: 'CTA Button Text', type: 'text' },
      { key: 'ctaUrl', label: 'CTA Button URL', type: 'url' },
      { key: 'bgImage', label: 'Background Image URL', type: 'url' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
      { key: 'bgOverlayOpacity', label: 'Background Color Opacity (0-100)', type: 'text' },
      { key: 'textColor', label: 'Text Color', type: 'color' },
    ],
    defaults: {
      title: 'Welcome to Our Website',
      subtitle: 'We build amazing digital experiences that captivate and convert.',
      ctaText: 'Get Started',
      ctaUrl: '#',
      bgImage: '',
      bgColor: '#0f172a',
      bgOverlayOpacity: '65',
      textColor: '#ffffff',
    },
  },
  {
    type: 'features',
    label: 'Features',
    description: 'Three-column feature highlights',
    fields: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'subtitle', label: 'Section Subtitle', type: 'text' },
      { key: 'feature1Title', label: 'Feature 1 Title', type: 'text' },
      { key: 'feature1Desc', label: 'Feature 1 Description', type: 'textarea' },
      { key: 'feature2Title', label: 'Feature 2 Title', type: 'text' },
      { key: 'feature2Desc', label: 'Feature 2 Description', type: 'textarea' },
      { key: 'feature3Title', label: 'Feature 3 Title', type: 'text' },
      { key: 'feature3Desc', label: 'Feature 3 Description', type: 'textarea' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
    ],
    defaults: {
      title: 'Why Choose Us',
      subtitle: 'Everything you need to build something great',
      feature1Title: 'Lightning Fast',
      feature1Desc: 'Optimized performance that keeps your users engaged and converts visitors.',
      feature2Title: 'Secure by Default',
      feature2Desc: 'Enterprise-grade security built in from the ground up, always.',
      feature3Title: 'Easy to Scale',
      feature3Desc: 'Grows seamlessly with your business from day one to millions.',
      bgColor: '#f8fafc',
    },
  },
  {
    type: 'stats',
    label: 'Stats',
    description: 'Key metrics and numbers',
    fields: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'stat1Number', label: 'Stat 1 Number', type: 'text' },
      { key: 'stat1Label', label: 'Stat 1 Label', type: 'text' },
      { key: 'stat2Number', label: 'Stat 2 Number', type: 'text' },
      { key: 'stat2Label', label: 'Stat 2 Label', type: 'text' },
      { key: 'stat3Number', label: 'Stat 3 Number', type: 'text' },
      { key: 'stat3Label', label: 'Stat 3 Label', type: 'text' },
      { key: 'stat4Number', label: 'Stat 4 Number', type: 'text' },
      { key: 'stat4Label', label: 'Stat 4 Label', type: 'text' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
      { key: 'textColor', label: 'Text Color', type: 'color' },
    ],
    defaults: {
      title: '',
      stat1Number: '10K+',
      stat1Label: 'Happy Customers',
      stat2Number: '99.9%',
      stat2Label: 'Uptime',
      stat3Number: '50+',
      stat3Label: 'Countries',
      stat4Number: '24/7',
      stat4Label: 'Support',
      bgColor: '#0f172a',
      textColor: '#ffffff',
    },
  },
  {
    type: 'testimonials',
    label: 'Testimonials',
    description: 'Customer reviews and quotes',
    fields: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'quote1', label: 'Quote 1', type: 'textarea' },
      { key: 'author1', label: 'Author 1 Name', type: 'text' },
      { key: 'role1', label: 'Author 1 Role', type: 'text' },
      { key: 'avatar1', label: 'Avatar 1 URL', type: 'url' },
      { key: 'quote2', label: 'Quote 2', type: 'textarea' },
      { key: 'author2', label: 'Author 2 Name', type: 'text' },
      { key: 'role2', label: 'Author 2 Role', type: 'text' },
      { key: 'avatar2', label: 'Avatar 2 URL', type: 'url' },
      { key: 'quote3', label: 'Quote 3', type: 'textarea' },
      { key: 'author3', label: 'Author 3 Name', type: 'text' },
      { key: 'role3', label: 'Author 3 Role', type: 'text' },
      { key: 'avatar3', label: 'Avatar 3 URL', type: 'url' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
    ],
    defaults: {
      title: 'What Our Clients Say',
      quote1: "This product completely transformed our workflow. We've saved 20 hours a week.",
      author1: 'Sarah Johnson',
      role1: 'CEO, TechCorp',
      avatar1: 'https://i.pravatar.cc/80?img=1',
      quote2: 'Incredible support team and an even better product. Highly recommended!',
      author2: 'Mark Davis',
      role2: 'CTO, StartupXYZ',
      avatar2: 'https://i.pravatar.cc/80?img=2',
      quote3: "The ROI we've seen since switching has been remarkable. Worth every penny.",
      author3: 'Emma Wilson',
      role3: 'Director, Agency Co',
      avatar3: 'https://i.pravatar.cc/80?img=3',
      bgColor: '#ffffff',
    },
  },
  {
    type: 'gallery',
    label: 'Gallery',
    description: 'Image grid showcase',
    fields: [
      { key: 'title', label: 'Section Title', type: 'text' },
      { key: 'subtitle', label: 'Section Subtitle', type: 'text' },
      { key: 'image1', label: 'Image 1 URL', type: 'url' },
      { key: 'image2', label: 'Image 2 URL', type: 'url' },
      { key: 'image3', label: 'Image 3 URL', type: 'url' },
      { key: 'image4', label: 'Image 4 URL', type: 'url' },
      { key: 'image5', label: 'Image 5 URL', type: 'url' },
      { key: 'image6', label: 'Image 6 URL', type: 'url' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
    ],
    defaults: {
      title: 'Our Work',
      subtitle: 'A selection of recent projects',
      image1: 'https://picsum.photos/seed/wb1/600/400',
      image2: 'https://picsum.photos/seed/wb2/600/400',
      image3: 'https://picsum.photos/seed/wb3/600/400',
      image4: 'https://picsum.photos/seed/wb4/600/400',
      image5: 'https://picsum.photos/seed/wb5/600/400',
      image6: 'https://picsum.photos/seed/wb6/600/400',
      bgColor: '#f8fafc',
    },
  },
  {
    type: 'cta',
    label: 'Call to Action',
    description: 'Conversion-focused banner',
    fields: [
      { key: 'title', label: 'Title', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'btnText', label: 'Button Text', type: 'text' },
      { key: 'btnUrl', label: 'Button URL', type: 'url' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
      { key: 'textColor', label: 'Text Color', type: 'color' },
      { key: 'btnBg', label: 'Button Background', type: 'color' },
      { key: 'btnTextColor', label: 'Button Text Color', type: 'color' },
    ],
    defaults: {
      title: 'Ready to Get Started?',
      description:
        'Join thousands of happy customers and start building something amazing today.',
      btnText: 'Start Free Trial',
      btnUrl: '#',
      bgColor: '#6366f1',
      textColor: '#ffffff',
      btnBg: '#ffffff',
      btnTextColor: '#6366f1',
    },
  },
  {
    type: 'footer',
    label: 'Footer',
    description: 'Page footer with links and copyright',
    fields: [
      { key: 'logo', label: 'Logo Text', type: 'text' },
      { key: 'tagline', label: 'Tagline', type: 'text' },
      { key: 'links', label: 'Links (comma-separated)', type: 'text' },
      { key: 'copyright', label: 'Copyright Text', type: 'text' },
      { key: 'bgColor', label: 'Background Color', type: 'color' },
      { key: 'textColor', label: 'Text Color', type: 'color' },
    ],
    defaults: {
      logo: 'MyBrand',
      tagline: 'Building the future, one pixel at a time.',
      links: 'Privacy Policy,Terms of Service,Contact',
      copyright: '© 2026 MyBrand. All rights reserved.',
      bgColor: '#0f172a',
      textColor: '#94a3b8',
    },
  },
]

export const getSectionDef = (type: string) =>
  SECTION_DEFINITIONS.find((d) => d.type === type)

export const SECTION_TYPE_LIST = SECTION_DEFINITIONS.map((d) => d.type as SectionType)
